#! /bin/bash
ZONE=$1

touch /etc/bind/zones/zone.$1

perl -i  -pe '/Serial/ && s/(\d+)/$1+1 . $2/e' /etc/bind/zones/db.jasper-vandenberghen.sb.uclllabs.be
perl -i  -pe '/Serial/ && s/(\d+)/$1+1 . $2/e' /etc/bind/zones/zone.$1

echo "zone \"$1.jasper-vandenberghen.sb.uclllabs.be\" {
        type master;
        file \"/etc/bind/zones/zone.$1\";
};" >>  /etc/bind/named.conf.mrt-zones


echo "\$TTL 360
@   IN SOA  ns.$1.jasper-vandenberghen.sb.ucclllabs.be. root.ns.jasper-vandenberghen.sb.uclllabs.be. (
                0       ; Serial
                3H      ; Refresh
                1H      ; Retry
                1W      ; Expire
                3H )    ; Negative Cache TTL

@               IN      NS      ns.jasper-vandenberghen.sb.uclllabs.be." > /etc/bind/zones/zone.$1


echo "$1              IN      NS       ns.jasper-vandenberghen.sb.uclllabs.be." >> /etc/bind/zones/db.jasper-vandenberghen.sb.uclllabs.be
echo "$1              IN      A        193.191.177.153" >> /etc/bind/zones/db.jasper-vandenberghen.sb.uclllabs.be

rndc reload
