#! /bin/bash
PREFIX="`echo $1 | awk -F . '{print $1}'`"
SUBDOMAIN="`echo $1 | awk -F . '{print $2}'`"

echo "$PREFIX"
echo "$SUBDOMAIN"

GREP=$(grep "$SUBDOMAIN[[:space:]]*IN[[:space:]]*A" /etc/bind/zones/db.$SUBDOMAIN.jasper-vandenberghen.sb.uclllabs.be)
if [ -z "$GREP" ];
then
echo "this prefix or subdomain does not exist here"
else
	mkdir /var/www/html/$PREFIX.$SUBDOMAIN
	touch /var/www/html/$PREFIX.$SUBDOMAIN/index.html
	echo 'welcome '$PREFIX.$SUBDOMAIN > /var/www/html/$PREFIX.$SUBDOMAIN/index.html

	touch /etc/apache2/sites-available/$PREFIX.$SUBDOMAIN.conf
	echo "<VirtualHost *:80>
	# This first listed virtual host is also the default for *:80
        	ServerName $1
        	DocumentRoot /var/www/html/$PREFIX.$SUBDOMAIN

        	LogLevel info
        	ErrorLog "${APACHE_LOG_DIR}"/$PREFIX.$SUBDOMAIN-error.log
        	CustomLog "${APACHE_LOG_DIR}"/$PREFIX.$SUBDOMAIN-access.log combined
	</VirtualHost>" > /etc/apache2/sites-available/$PREFIX.$SUBDOMAIN.conf

	a2ensite $PREFIX.$SUBDOMAIN

	systemctl reload apache2
fi
